customer.params.x=11
customer.params.y=22
global.params.p1=some_value  # <- Add this line
spring.datasource.url=jdbc:h2:mem:customers-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.h2.console.enabled=true
spring.data.rest.base-path=/api
